[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Ruofeng Lei", email = "ruofenglei@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "rich>=15.0.0",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
